### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Ka1der** [Zabriskije/SD-to-CoreML#2]
Hi. The script doesn't work. Gives an error message. Can't find the model.

Traceback (most recent call last):
  File "convert_original_stable_diffusion_to_diffusers.py", line 160, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/Users/kaider/miniconda3/envs/coreml_stable_diffusion/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1252, in download_from_original_stable_diffusion_ckpt
    checkpoint = safe_load(checkpoint_path_or_dict, device="cpu")
  File "/Users/kaider/miniconda3/envs/coreml_stable_diffusion/lib/python3.8/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: "icbinpICantBelieveIts_lcm.safetensors"
<img width="567" alt="Снимок экрана 2023-12-24 в 19 58 21" src="https://github.com/Zabriskije/SD-to-CoreML/assets/60022026/378bf690-1666-4a16-8f10-a71e8fa2936c">

**Comment by Zabriskije** [comment]
Have you edited the `sd-to-coreml.sh` file to match your custom paths?

```
# If Miniconda has been installed in a different folder from your home one, change "YOUR-PATH-HERE" with your custom path. Otherwise, simply delete it
source ~/YOUR-PATH-HERE/miniconda3/etc/profile.d/conda.sh
conda activate coreml_stable_diffusion

# Change "YOUR-PATH-HERE" with your Diffusers script and model's path
cd ~/YOUR-PATH-HERE
```

Also, I don't see the [convert_original_stable_diffusion_to_diffusers.py](https://github.com/huggingface/diffusers/raw/main/scripts/convert_original_stable_diffusion_to_diffusers.py) script in the model's folder.

**Comment by Ka1der** [comment]
Yes. Paths edited.
<img width="800" alt="Снимок экрана 2023-12-24 в 21 41 50" src="https://github.com/Zabriskije/SD-to-CoreML/assets/60022026/7e062d12-87fc-4c4f-ba9c-352555f5b911">

I put the file in a folder. But it did not help

<img width="480" alt="Снимок экрана 2023-12-24 в 22 02 29" src="https://github.com/Zabriskije/SD-to-CoreML/assets/60022026/3395bb40-9fb8-4c0e-b9e5-196e69a7a17f">

<img width="754" alt="Снимок экрана 2023-12-24 в 22 02 14" src="https://github.com/Zabriskije/SD-to-CoreML/assets/60022026/f7f5d376-10cb-4f59-a217-54d727c2f74f">

**Comment by Zabriskije** [comment]
The specified path is `Users/kaider/miniconda3/pkgs` but the folder in the screenshot is named `SD-to-CoreML-1.3a`, so perhaps the problem could be this? The path present in the script should be the same as the folder that contains your model, script, and Python file.

**Comment by Ka1der** [comment]
I put the file in the folder with the script, pointed to the file path and it helped. Thank you. Safetensors has been recoded to Diffusers. But when converting to splineinsum, the new file is again missing.

Where can I get this file?
Should I put it in /Users/kaider/miniconda3/envs/coreml_stable_diffusion/bin/ ?

<img width="571" alt="Снимок экрана 2023-12-25 в 20 06 42" src="https://github.com/Zabriskije/SD-to-CoreML/assets/60022026/daaf012c-c9c5-4e86-bfc4-2f619098b122">

**Comment by Zabriskije** [comment]
Try typing in the terminal `conda activate coreml_stable_diffusion`, then `pip install python_coreml_stable_diffusion`.

**Comment by Ka1der** [comment]
Some problem with version.... python?
I have 3.8.18
<img width="586" alt="Снимок экрана 2023-12-25 в 20 56 34" src="https://github.com/Zabriskije/SD-to-CoreML/assets/60022026/f22be63d-fdd9-4762-864d-6bee6fd21c1f">

**Comment by Zabriskije** [comment]
I don't know exactly what can cause this. Could you try deleting the Conda env (`conda env remove --name coreml_stable_diffusion`), the ml-stable-diffusion repo, and install it again? Basically from point 5 of the [Prerequisites](https://github.com/Zabriskije/SD-to-CoreML#prerequisites).

**Comment by Ka1der** [comment]
That helped! I removed the Conda command (`conda env remove --name coreml_stable_diffusion`) and followed all the steps in the Prerequisites section again.
I was able to convert safetensors -> diffusers -> split-einsum (mlmodels).
Thank you!

**Comment by Zabriskije** [comment]
You're welcome. Sometimes it happens, so save that command somewhere ;)
